### ISSUE TITLE
Gestire le richieste d'ammissione

### ISSUE THREAD

**Issue by dario2994** [walypala23/correzioni-olimpiadi#36]
Sarebbe comodo, e quasi indipendente dal resto, quindi facile, aggiungere la possibilità di fare richiesta d'ammissione direttamente sul sito delle correzioni, così non ci sarebbe neanche più la fatica della creazione di tutti i partecipanti. È un lavoro abbastanza grosso, ma che non dovrebbe presentare intoppi (tranne forse l'upload di grossi file).

p.s. Quando lo si fa, chiedere informazioni a Sam riguardo cosa si deve poter fare e cosa no.

**Comment by dario2994** [comment]
Imporre un limite (100? 150? 300? 500?) al numero di possibili partecipanti ad una gara. Imporre un limite sulla grandezza del documento (10Mb? 30Mb? 100Mb?). Quando qualcuno si iscrive ad una gara è il caso di registrare qualcosa che lo identifichi (ip e useragent?) e magari (ma questo è un overkill) aggiungere un captcha per evitare bot.

I documenti inviati vanno controllati accuratamente (non solo che sembrino pdf, ma che lo siano) e vanno salvati fuori dalla root del server (altrimenti potrebbero accederci senza averne i diritti).

**Comment by walypala23** [comment]
Informazioni da richiedere alla registrazione:
* Nome e cognome
* Indirizzo email
* Scuola
* Anno di corso
* Numero di "pise"
* Volontario o spesato
* Pdf con gli esercizi
* Pdf con la domanda di ammissione per i volontari (da poi inviare all'UMI tramite mail)

Come sicurezza, si potrebbe aggiungere una verifica tramite un codice via email.

**Comment by dario2994** [comment]
Serve anche la provenienza geografica?

**Comment by dario2994** [comment]
Dopo un lungo lavoro tutto questo è stato implementato. 
Sul server non viene salvato se è volontario o spesato e la domanda d'ammissione (questi dati vengono solo inviati per mail al giusto destinatario). Però viene salvata la città della scuola. 
La sicurezza è assicurata da un codice mandato via email.
