### ISSUE TITLE
Commenti troncati

### ISSUE THREAD

**Issue by fph** [walypala23/correzioni-olimpiadi#39]
Mi è già capitato un paio di volte che i commenti delle correzioni venissero troncati quando li sottomettevo. L'ultima volta stamattina con A4-P di Fratianni. Il commento è stato troncato a 124 caratteri, cioè due righe. Il primo carattere troncato era un <, mi sembra.

**Comment by dario2994** [comment]
Ho provato a realizzare il bug e forse ho capito cosa succede. 
Se nel commento scrivi **\<pici\>** (o qualunque carattere speciale tipo **\<\>\&**) quando si invia scompaiono un po' di cose (ciò è dovuto ad un comportamento di textContent che non conoscevo e che è raccontato [qui](http://benv.ca/2012/10/02/you-are-probably-misusing-DOM-text-methods/)), ma sul server viene salvato tutto correttamente e se si aggiorna la pagina tutto compare come dovrebbe. Probabilmente però tu, vedendo il bug hai modificato il commento senza riaggiornare prima e questo ha fatto sì che poi quando hai inviato la seconda volta il commento venisse troncato anche sul server.

Questo problema l'ho risolto, ma se invece tu **non** hai rimodificato il commento troncato prima di aggiornare la pagina allora non è questo il problema che ti si presenta.

Attualmente il fix non è sul sito delle correzioni (e preferirei non modificare nulla (a meno di cose drammatiche) prima della fine delle correzioni del senior) e quindi il "vecchio" bug si potrebbe presentare ancora. Nel caso prova ad aggiornare subito la pagina, se tutto torna giusto allora il problema è ora risolto, altrimenti ho risolto un altro bug.

p.s. Puoi aggiustare il commento di Fratianni ora.
p.p.s. Questo bug è dovuto alla soluzione che avevo trovato per quest'altro problema #34.

**Comment by fph** [comment]
Ok, grazie mille. Sono d'accordo con te nel non voler cambiare nulla intanto che le correzioni sono in corso.
