### ISSUE TITLE
Mail a meno di punti

### ISSUE THREAD

**Issue by dario2994** [walypala23/correzioni-olimpiadi#54]
Indirizzi email che coincidono a meno di punti '.' vanno considerati uguali (visto che nelle mail i punti sono ignorati).
Perciò dovrebbe essere impossibile registrarsi con un indirizzo che coincide, a meno di punti, con uno già presente. 
La modifica andrebbe resa retroattiva, cioè utenti con mail "analoghe" devono essere uniti.

**Comment by fph** [comment]
"nelle mail i punti sono ignorati" -- no, solo in gmail (e credo anche nei domini gestiti da gmail, tipo sns.it). In generale, i punti possono differenziare indirizzi. Sources: https://stackoverflow.com/questions/14865869/ https://apple.stackexchange.com/questions/126697/ http://gmail-miscellany.blogspot.it/2012/08/wrong-email-gmail-dots-issue.html

**Comment by dario2994** [comment]
Hai ragione in pieno.
